#coupon-distribution 分发微服务
server:
  port: 7002
  servlet:
    context-path: /coupon-distribution
#服务名称
spring:
  application:
    name: eureka-client-coupon-distribution
  #redis
  redis:
    database: 0
    host: 192.168.0.102
    port: 6379
    timeout: 10000

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.show_sql: true
      hibernate.format_sql: true
    open-in-view: false



  #mysql datasourse
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.0.102:3306/imooc_coupon_data?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

#eureka 注册
eureka:
  client:
    service-url:
      defaultZone: http://192.168.0.102:8000/eureka/
#日志
logging:
  level:
    com.imooc.coupon: debug
  kafka:
    bootstrap-servers:  -127.0.0.1:9092

    consumer:
      group-id: imooc-coupon-x
      auto-offset-reset: latest
  # 开启 ribbon 重试机制, 即获取服务失败是否从另外一个节点重试
  cloud:
    loadbalancer:
      retry:
        enabled: true


# feign 相关的配置
feign:
  hystrix:
    enabled: true   # Hystrix 默认是关闭的
  client:
    config:
      default:  # 全局的
        connectTimeout: 2000  # 默认的连接超时时间是 10s
        readTimeout: 5000
      eureka-client-coupon-template:  # 单独服务的配置
        connectTimeout: 3000  # 默认的连接超时时间是 10s
        readTimeout: 5000


