#端口
server:
  port: 8000
#项目名字
spring:
  application:
    name: coupon-eureka


#eureka
eureka:
  instance:
    hostname: localhost
    #标识是否从Eureka Server 获取注册信息,如果是一个单节点的Eureka Server
    #不需要同步其他节点的数据
  client:
    fetch-registry: false
    #标识是否将自己注册到Eureka Server,默认是ture,单节点不需要false
    register-with-eureka: false
    #设置Eureka Server所在的地址,查询服务和注册服务都需要依赖这个地址
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

